### PR TITLE
Add an ability to choose the micro:bit port using environment variables

### PR DESCRIPTION
**Pull request by musabkilic**
Pull request for #40 

Works by setting the env variable `PORT`

### CODE REVIEW

**Comment by whaleygeek** [comment]
Nice.

Can I suggest you call it BITIO_PORT, and also add a line to the readme explaining that this variable exists and what it is for, and how to set it.

Thanks!

**Comment by musabkilic** [comment]
Done!

**Comment by whaleygeek** [comment]
Great thanks!

**Comment by whaleygeek** [comment]
Thanks for your contribution!

**Pull request merged**
